export const messages = {
    en: {
        cart: 'Cart',
        language: 'Language',
        addToCart: 'Add to cart',
        english: 'English',
        arabic: 'العربية',
        home: 'Home',
        shop: 'Shop',
        product: 'Product',
        checkOut: 'Check Out',
        category: 'Category',
        others: 'Others',
        contact: 'Contact',
        myCart: 'My Cart',
        applyCoupon: 'Apply Coupon',
        searchProduct: 'Search Products',
        products: 'Products',
        search: 'SEARCH',
        coupon: 'Coupon',
        couponCode: 'Coupon code',
        cartTotal: 'Cart Totals',
        cartSubTotal: 'Cart Subtotal',
        shippingAndHandling: 'Shipping and Handling',
        freeShipping: 'Free Shipping',
        orderTotal: 'Order Total',
        discount: 'Discount',
        shoppingCart: 'Shopping Cart',
        login: 'Login',
        firstName: 'First Name',
        lastName: 'Last Name',
        password: 'Password',
        confirmPassowrd: 'Confirm Password',
        aed: 'AED',
        mobile: 'Phone Number',
        email: 'Email',
        signIn: 'Sign In?',
        signUp: 'Sign Up?',
        myAccount: 'My Account',
        logOut: 'Log Out',
        shippingAddress: 'Shipping Address',
        address: 'Address',
        pinCode: 'Pincode',
        area: 'Area',
        landmark: 'Landmark',
        city: 'City',
        state: 'State',
        addressType: 'Address Type',
        selectAddressType: 'Select Address type',
        fullName: 'Full Name',
        office: 'Office',
        save: 'Save',
        add: 'Add',
        checkToCreate: 'Check to create',
        edit: 'Edit',
        payment: 'Payment',
        placeOrder: 'Place Order',
        price: 'Price',
        total: 'Total',
        quantity: 'Quantity',
        startShopping : 'START SHOPPING',
        orderPlaceSuccessfully: 'Order Placed successfully',
        orderDetails: 'Order Details',
        productImage: 'Product Image',
        paymentMethod: 'Payment Method',
        couponCodeAppiedSuccessfully: 'Coupon Code Applied Successfully.',
        notFound: 'not found.',
        noResultFound: 'No result found.',
        credentialNotFound: 'Credential not found!',
        register: 'Register',
        dryFruits: 'Dry Fruits',
        snacks: 'Snacks',
        about: 'About',
        featureProductrs: 'Featured Products',
        latestProduct : 'Latest Products',
        recentlyViewed: 'Recently Viewed',
        mostViewed: 'Most Viewed',
        shopMore: 'Shop More',
        removeCoupon: 'Remove Coupon',
        successCouponCode: 'Coupon successfully applied.',
        successCouponCodeRemoved: 'Coupon successfully removed.',
        orderSummary: 'Order summary',
        cartItemRemoved: 'Cart item removed',
        totalPrice: 'Total Price',
        delete: 'Delete',
        cartItemAdd: 'Product added to cart successfully',
        close: "Close",
        update: 'Update',
        createShippingAddress: 'Create Shipping Address',
        streetAddress1: 'Street Address 1',
        streetAddress2: 'Street Address 2',
        name: 'Name',
        shippingAddressDeletedSuceessfully: 'Shipping Address Deleted Suceessfully.',
        nameOnCard: 'Name on card',
        cardNumber: 'Card number',
        expiryDate: 'Expiry date',
        cvv: 'CVV',
        payNow: 'Pay now',
        menu: 'Menu',
        contactUs: 'Contact Us',
        contactInfo: 'Contact Info',
        shippingCharge: 'Shipping Charge',
        in: 'In',
        create: 'Create',
        pay: 'Pay',
        cod: 'COD',
        with: 'With',
        quantity: 'Quantity',
        description: 'Description',
        review: 'Review',
        writeReview: 'Write Review',
        rating: 'Rating',
        reviewTitle: 'Review Title',
        writereview: 'Write Review',
        writeyourreview: 'Write your review',
        nameNDate: 'Name & Date',
        notLoggedIn: 'Your are not logged in.',
        subTotal: 'Sub-Total',
        thankYou: 'Thank You',
        myProfile: 'My Profile',
        changePassword: 'Change Password',
        myOrders: 'My Orders',
        countryCode: 'Country Code',
        oldpassword: 'Old Password',
        newpassword: 'New Password',
        profileUpdatedSuccessfully: 'Profile Updated Successfully',
        passwordChangeSuccessfully: 'Password Change Successfully',
        orderId: 'Order Id',
        orderDate: "Order Date",
        back: 'Back',
        productInfo: 'Product Information',
        copyRight: 'Copyright',
        allRightReserved: '2019. All Rights Reserved.',
        designAndDeveloperdBy: 'Design & Development by',
        forgotPassword: 'Forgot Password',
        sendPasswordResetLink: 'Send Password Reset Link',
        emailPasswordLink: 'We have e-mailed your password reset link!',
        cartMustBeGreateThanZero: 'Cart must be greater than zero',
        alertDeleteMessage: 'Are you sure want to delete ?',


    },
    ar: {
        cart: 'عربة التسوق',
        language: 'لغة',
        addToCart: 'أضف إلى السلة',
        english: 'English',
        arabic: 'العربية',
        home: 'الصفحة الرئيسية',
        shop: 'متجر',
        product: 'المنتج',
        checkOut: 'الدفع',
        category: 'الفئة',
        others: 'الآخرين',
        contact: 'اتصل',
        myCart: 'سلتي',
        applyCoupon: 'تطبيق القسيمة',
        searchProduct: 'البحث عن المنتجات',
        products: 'منتجات',
        search: 'تقص',
        coupon: 'قسيمة',
        couponCode: 'رمز القسيمة',
        cartTotal: 'إجماليات السلة',
        cartSubTotal: 'المجموع الفرعي للعربة',
        shippingAndHandling: 'الشحن والمناولة',
        freeShipping: 'الشحن مجانا',
        orderTotal: 'الطلب الكلي',
        discount: 'خصم',
        shoppingCart: 'عربة التسوق',
        login: 'تسجيل الدخول',
        firstName: 'الاسم الاول',
        lastName: 'الكنية',
        password: 'كلمه السر',
        confirmPassowrd: 'تأكيد كلمة المرور',
        aed: 'د.إ',
        mobile: 'التليفون المحمول',
        email: 'البريد الإلكتروني',
        signIn: 'تسجيل الدخول؟',
        signUp: 'سجل؟',
        myAccount: 'حسابي',
        logOut: 'الخروج',
        shippingAddress: 'عنوان الشحن',
        address: 'عنوان',
        pinCode: 'الرقم السري',
        area: 'منطقة',
        landmark: 'معلم معروف',
        city: 'مدينة',
        state: 'حالة',
        addressType: 'نوع العنوان',
        selectAddressType: 'اختر نوع العنوان',
        fullName: 'الاسم الكامل',
        office: 'مكتب. مقر. مركز',
        save: 'حفظ',
        add: 'إضافة',
        checkToCreate: 'تحقق لإنشاء',
        edit: 'تصحيح',
        payment: 'دفع',
        placeOrder: 'مكان الامر',
        price: 'السعر',
        total: 'مجموع',
        quantity: 'كمية',
        startShopping : 'ابدأ التسوق',
        orderPlaceSuccessfully: 'تم وضع الطلب بنجاح',
        orderDetails: 'تفاصيل الطلب',
        productImage: 'صورة المنتج',
        paymentMethod: 'طريقة الدفع او السداد',
        couponCodeAppiedSuccessfully: 'تم تطبيق كود القسيمة بنجاح.',
        notFound: 'غير معثور عليه.',
        noResultFound: 'لم يتم العثور على نتائج.',
        credentialNotFound: 'بيانات الاعتماد غير موجودة!',
        register: 'تسجيل',
        dryFruits: 'فواكه مجففة',
        snacks: 'وجبات خفيفة',
        about: 'حول',
        featureProductrs: 'منتجات مميزة',
        latestProduct : 'أحدث المنتجات',
        recentlyViewed: 'شوهدت مؤخرا',
        mostViewed: 'الأكثر مشاهدة',
        shopMore: 'تسوق أكثر',
        removeCoupon: 'إزالة القسيمة',
        successCouponCode: 'تم تطبيق الكوبون بنجاح.',
        successCouponCodeRemoved: 'تمت إزالة القسيمة بنجاح.',
        orderSummary: 'ملخص الطلب',
        cartItemRemoved: 'تمت إزالة عنصر السلة',
        totalPrice: 'السعر الكلي',
        delete: 'حذف',
        cartItemAdd: 'تم اضافة المنتج الى السلة بنجاح',
        close: "قريب",
        update: 'تحديث',
        createShippingAddress: 'إنشاء عنوان الشحن',
        streetAddress1: 'عنوان الشارع 1',
        streetAddress2: 'عنوان الشارع 2',
        name: 'اسم',
        shippingAddressDeletedSuceessfully: 'عنوان الشحن محذوف بنجاح.',
        nameOnCard: 'الاسم على البطاقة',
        cardNumber: 'رقم البطاقة',
        expiryDate: 'تاريخ الانتهاء',
        cvv: 'CVV',
        payNow: 'ادفع الآن',
        menu: 'قائمة طعام',
        contactUs: 'اتصل بنا',
        contactInfo: 'معلومات الاتصال',
        shippingCharge: 'رسوم الشحن',
        in: 'على',
        create: 'خلق',
        pay: 'دفع',
        cod: 'الدفع عن الاستلام',
        with: 'مع',
        quantity: 'كمية',
        description: 'وصف',
        review: 'إعادة النظر',
        writeReview: 'أكتب مراجعة',
        rating: 'تقييم',
        reviewTitle: 'مراجعة العنوان',
        writereview: 'أكتب مراجعة',
        writeyourreview: 'اكتب مراجعتك',
        nameNDate: 'الاسم والتاريخ',
        notLoggedIn: 'انت غير مسجل الدخول.',
        subTotal: 'المجموع الفرعي',
        thankYou: 'شكرا جزيلا',
        myProfile: 'ملفي',
        changePassword: 'غير كلمة السر',
        myOrders: 'طلباتي',
        countryCode: 'كود البلد',
        oldpassword: 'كلمة المرور القديمة',
        newpassword: 'كلمة السر الجديدة',
        profileUpdatedSuccessfully: 'تم تحديث الملف الشخصي بنجاح',
        passwordChangeSuccessfully: 'تغيير كلمة المرور بنجاح',
        orderId: 'رقم التعريف الخاص بالطلب',
        orderDate: "تاريخ الطلب",
        back: 'ظهر',
        productInfo: 'معلومات المنتج',
        copyRight: 'حقوق النشر',
        allRightReserved: '2019. جميع الحقوق محفوظة..',
        designAndDeveloperdBy: 'تصميم وتطوير بواسطة',
        forgotPassword: 'هل نسيت كلمة المرور',
        sendPasswordResetLink: 'إرسال رابط إعادة تعيين كلمة المرور',
        emailPasswordLink: 'لقد أرسلنا رابط إعادة تعيين كلمة المرور عبر البريد الإلكتروني!',
        cartMustBeGreateThanZero: 'يجب أن تكون السلة أكبر من الصفر',
        alertDeleteMessage: 'هل تريد بالتأكيد الحذف؟',

        
    }
}
